### ISSUE TITLE
[cordova-windows] dealing with template/Properties/Default.rd.xml

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-discuss#106]
I have uncovered a couple issues with `template/Properties/Default.rd.xml`:
- [CB-14224](https://issues.apache.org/jira/browse/CB-14224) - running `coho audit-license-headers -r windows` gives a message that `template/Properties/Default.rd.xml` is missing the license header
- [CB-14225](https://issues.apache.org/jira/browse/CB-14225) - misspelling in sample Namespace serialize attribute name

along with an additional issue that seems to be unsolved:
- [CB-13834](https://issues.apache.org/jira/browse/CB-13834) - problem building with  build with params `--release --bundle --archs="x64 x86 arm"` on AppVeyor CI

I start to wonder if we should even keep `template/Properties/Default.rd.xml` in future releases. The following observations indicate to me that xxxx is only needed for projects using C# plugins:
- If I would try generating both a JavaScript UWP project and a C# UWP project then VS 2017 would only add `Properties/Default.rd.xml` in case of C#.
- [Microsoft / Windows-universal-samples](https://github.com/Microsoft/Windows-universal-samples) keeps its sample `Default.rd.xml` in a `cs` directory ([Microsoft / Windows-universal-samples / SharedContent / cs / Default.rd.xml](https://github.com/Microsoft/Windows-universal-samples/blob/master/SharedContent/cs/Default.rd.xml)

I can think of the following possible alternatives:
- add license text and fix Namespace Serialize attribute name as proposed in apache/cordova-windows#284, apache/cordova-windows#285, and apache/cordova-windows#286
- configure Apache RAT to skip `template/Properties/Default.rd.xml` and fix sample Namespace Serialize attribute (apache/cordova-windows#286) (I haven't tried this yet)
- remove `template/Properties/Default.rd.xml` in upcoming major release
- make it optional to include `Properties/Default.rd.xml` in generated project
- handle `Properties/Default.rd.xml` in a plugin (if possible)

**Comment by janpio** [comment]
I ignored this problem and file with the last release because it was not that easy to find out more about it.

But the PR that added this file indicates it is there for a reason:

>  CB-12499 UWP: Dependent external libraries specified as resource-file not being referenced in Release mode
> 
> Adds Default.rd.xml to Windows 10 project template making an app metadata to be available for reflection at runtime

https://github.com/apache/cordova-windows/commit/d5ddcb4c4f546d2aa7707b57b26c5143ff42c91f#diff-c54bf1c523e7312aae8e89dc03ae16dd

Original JIRA issue with more context:
https://issues.apache.org/jira/browse/CB-12499

(As `cordova-windows` has issues, this issue here could very well be placed over there instead of in this unconnected repo)

**Comment by brodybits** [comment]
Continued in apache/cordova-windows#228
