### ISSUE TITLE
cordova and languages in projects 

### ISSUE THREAD

**Issue by jcesarmobile** [apache/cordova-discuss#25]
Yesterday I saw this issue
https://issues.apache.org/jira/browse/CB-9789 (camera plugin doesn't use the native iOS language)

And I was going to close as some other older duplicated
https://issues.apache.org/jira/browse/CB-1857
https://issues.apache.org/jira/browse/CB-3213

Let me explain the problem, iOS native components show the UI in the project languages and not in the device laguage, and cordova ios projects are created in english (all native projects are created in english by default), the language can be changed on the info.plist changing this line

```
<key>CFBundleDevelopmentRegion</key>
<string>English</string>
```

But that issue made me think, is there a way of creating cordova projects in other languages or make them multilingual? 
Cordova apps are created with html, css and javascript, so you can display the UI in any language you want or make it multilingual with different techniques, but that only makes your app multilingual not the project, so on the eyes of the stores (at least on the apple store, your app will be just in english, not sure about others) and you will have problems like the mentioned on the previous issues.

I've found this issue proposing "language flags for app stores" https://issues.apache.org/jira/browse/CB-7103

So, should we do something about it? manage project languages on config.xml? a core plugin? or a 3rd party plugin?

**Comment by PerfectionCSGO** [comment]
This may particulary be nice to have for tools for cordova visual studio. There are already cordova plugins out there that 'get' the locale values.

**Comment by dpogue** [comment]
The W3C Widgets spec (which config.xml is derived from) allows a `defaultlocale` attribute on the `<widget>` tag: https://www.w3.org/TR/widgets/#the-defaultlocale-attribute

A similar question around how to handle localized text was raised in https://github.com/apache/cordova-lib/pull/453
