### ISSUE TITLE
cordova-android 6.0.0 (installed by cordova-cli 6.4.0) drops result with u2028/u2029

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-discuss#57]
Similar to [Apache Cordova CB-9435 (cordova-ios)](https://issues.apache.org/jira/browse/CB-9435) _(will not be fixed, also an issue on macOS ["osx"])_: after upgrading to Cordova CLI 6.4.0 (which seems to use cordova-android@6.0.0) my sqlite plugin cannot return results with `u2028` (line separator) or `u2029` (paragraph separator) characters.

I don't expect this to be an issue on Windows since Cordova does not seem to use JSON on that platform. ~~(I will test and confirm when I get a chance.)~~ _UPDATE: Confirming this is NOT an issue on the Windows platform. I am not sure about the **deprecated** wp8 platform._

I will understand if this is not fixed for Android or iOS but would like to see this limitation documented. I will raise this on Apache Cordova JIRA and contribute this when I get a chance.

**Comment by timbru31** [comment]
I'm closing this stale issue, I bet this already has been solved.
