### ISSUE TITLE
Document why "AnyCPU" platform is dropped for Windows 10 UWP

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-discuss#59]
Over the past 1-2 years I noticed that if I would use the Cordova CLI to add the Windows platform build and then open the Visual Studio Solution file with the Visual Studio (2015) GUI it would select the "Any CPU" platform by default. This was good for Windows 8.1 and Windows Phone 8.1 for WinJS apps without SQLite since almost other plugins have been JavaScript only. I found a nice article for reference that seems to be duplicated somehow:
- <http://blogs.microsoft.co.il/sasha/2012/04/04/what-anycpu-really-means-as-of-net-45-and-visual-studio-11/>
- <https://dzone.com/articles/what-anycpu-really-means-net>

Then I found out that Microsoft did not really want to support the "Any CPU" target platform for Windows 10 UWP. I discovered that if I would build a test app with no plugins I could run an "Any CPU" build in Debug mode but not release mode.

From an unrelated discussion (https://github.com/litehelpers/Cordova-sqlite-storage/issues/610) I searched for information about an `<EnableDotNetNativeCompatibleProfile>` setting and found this question: <http://stackoverflow.com/questions/29979047/windows-universal-app-no-any-cpu-configuration-for-windows-10>

With some more searching I discovered why: .NET Native ref: <https://blogs.windows.com/buildingapps/2015/08/20/net-native-what-it-means-for-universal-windows-platform-uwp-developers/>

I wish this were documented more clearly for Cordova users, on a blog for example.

**Comment by jcesarmobile** [comment]
closing since the platform is now deprecated
