### ISSUE TITLE
Deprecate cordova-plugin-device-motion

### ISSUE THREAD

**Issue by macdonst** [apache/cordova-discuss#66]
I think it is time that we deprecate `cordova-plugin-device-motion`. The plugin follows an old API and is no longer the standard way to get accelerometer information from devices. Instead we should be following the [DeviceOrientation Event Specification](https://www.w3.org/TR/orientation-event/) which is already well supported in iOS 9.3+ and Android 4.4+. 

The last actual code commit was November of 2016.

Let's deprecate it and close the 7 open issues.

**Comment by purplecabbage** [comment]
cordova also supports windows universal as a core platform, so we need to verify how well supported the latest DeviceOrientation event spec is supported there.
Assuming all is good there ... +1

**Comment by purplecabbage** [comment]
Done!
