### ISSUE TITLE
[Proposal] package.json repos should link to github

### ISSUE THREAD

**Issue by purplecabbage** [apache/cordova-discuss#67]
Now that we are fully in this npm registry thing, I think we should update where repos point to in each package.json.

Currently if a user visits npmjs.org and views one of our packages [1] , the link takes them to the apache repos site [2].  At this point I think most users would slowly back away as no one really interacts with our repos there directly except for committers.

If however, we pointed to the github mirror [3], users might go, okay, here it is, okay I know how this works, forking ...
and send us pull requests!

The github mirror is in fact the place I would expect most people will interact with our repos, I myself have created all my forks from our github mirrors, after which I added remotes to git-wip-us.
I think this will help users discovering our packages as well as drive metrics like fork count, stars and other things that we don't typically care about that are used by others to determine the overall health of a project. To me this is all upside.

[1] https://www.npmjs.com/package/cordova
[2] https://git-wip-us.apache.org/repos/asf?p=cordova-cli.git
[3] https://github.com/apache/cordova-cli

**Comment by shazron** [comment]
👍  This is excellent for new contributors and discovery, and is the 21st century way forward.

**Comment by filmaj** [comment]
👍, make it so 👉

**Comment by stevengill** [comment]
Do it

**Comment by jcesarmobile** [comment]
Do it

**Comment by kerrishotts** [comment]
+1

**Comment by purplecabbage** [comment]
created!
https://issues.apache.org/jira/browse/CB-12762

**Comment by purplecabbage** [comment]
Issue closed.
Thanks @audreyso !
I also updated a bunch of dead repos ... for fun.
