### ISSUE TITLE
Gradle & Android Gradle Plugin updates recommended

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-discuss#85]
If I would create a Cordova project with Android platform (`cordova-android@7.0.0`) and then import the generated `platforms/android` as a Gradle project in Android Studio I get the following dialog:

![screen shot 2018-01-03 at 9 02 14 pm](https://user-images.githubusercontent.com/1559888/34547556-e8769580-f0c9-11e7-8112-936942990be6.png)

**Comment by janpio** [comment]
This is not a bug tracker for Cordova. Please open an issue at http://issues.cordova.io
