### ISSUE TITLE
Merge cordova-app-hello-world and cordova-template-reference

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova-discuss#91]
Right now, I need to record changes to template best practices in three places:

- [cordova-app-hello-world](https://github.com/apache/cordova-app-hello-world)
- [cordova-template-reference](https://github.com/apache/cordova-template-reference)
- [The template docs](https://cordova.apache.org/docs/en/latest/guide/cli/template.html)

I don't see why `cordova-app-hello-world` should not be default template and template reference at the same time.

**Comment by shazron** [comment]
👍🏼

**Comment by raphinesse** [comment]
There are not many refrences to cordova-template-reference:
https://github.com/search?l=&q=cordova-template-reference+user%3Aapache&type=Code

**Comment by raphinesse** [comment]
Resolved by the PRs linked above
