### ISSUE TITLE
cordova-serve release needed from master

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-discuss#95]
From @ruslan-bikkinin (with links fixed):

Hello again Cordova team.

I am looking forward to hearing from you.

--
Best regards,
Ruslan

From: "Ruslan Bikkinin (Akvelon)" <*****@microsoft.com>
Date: Tuesday, May 29, 2018 at 2:22 PM
To: "dev@cordova.apache.org" <dev@cordova.apache.org>
Cc: "Artem Egorov (Akvelon)" <*****@microsoft.com>, "Sergey Akhalkov (Akvelon)" <*****@microsoft.com>, Dhanvi Kapila <*****@microsoft.com>

Subject: Request for releasing new cordova-serve version

I am maintainer of [Microsoft / cordova-simulate](https://github.com/Microsoft/cordova-simulate) and [Microsoft / vscode-cordova](https://github.com/Microsoft/vscode-cordova) repos and we have a couple of issues (Microsoft/cordova-simulate#257, Microsoft/vscode-cordova#371) that took place because [apache / cordova-serve](https://github.com/apache/cordova-serve) repo didn’t support Cordova 7+ for android. However, this PR <https://github.com/apache/cordova-serve/pull/7> provides a fix that already have been merged into master a week and a half ago but no new version has been released. Could you please release new version of cordova-serve so we could use it to fix issues that affects our repos?

--
Best regards,
Ruslan

**Comment by brodybits** [comment]
My bad for submitting without description, just entered the email and quoting below for reference:

> I am maintainer of Microsoft / cordova-simulate and Microsoft / vscode-cordova repos and we have a couple of issues (Microsoft/cordova-simulate#257, Microsoft/vscode-cordova#371) that took place because apache / cordova-serve repo didn’t support Cordova 7+ for android. However, this PR apache/cordova-serve#7 provides a fix that already have been merged into master a week and a half ago but no new version has been released. Could you please release new version of cordova-serve so we could use it to fix issues that affects our repos?

**Comment by brodybits** [comment]
@ruslan-bikkinin I cross-posted your request to <phonegap@googlegroups.com> and requested this on the PMC channel. Hope this helps.

**Comment by brodybits** [comment]
They should be able to make the release sometime next week. Please send a followup to ALL of the following places if you do not see the needed release by the end of next week:
- this issue
- <dev@cordova.apache.org>
- <brodybits@litehelpers.net>

/cc @dpogue

**Comment by dpogue** [comment]
The issue for tracking this release is https://issues.apache.org/jira/browse/CB-14122

**Comment by dpogue** [comment]
cordova-serve@2.0.1 has been published
