### ISSUE TITLE
Rename "osx" platform in a major release?

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-discuss#96]
Idea from discussion in apache/cordova-common#32, thought of it myself over the past 1-2 years.

I would personally favor something like "mac" _(slightly favored by myself: short and sweet, unquestionably one word)_ or perhaps"macos" _(may be better consistency as described by Shazron)_.

**Comment by erisu** [comment]
I also favor the idea of renaming to either `mac` or `macos`. I don't have any preference over the two, but wouldn't mind helping out in the process once decided.

**Comment by shazron** [comment]
Personally I would favor `macos` to be consistent with `ios`. Initially it was `phonegap-mac`, then it was `cordova-osx` before Apple changed it to `macOS`

**Comment by dpogue** [comment]
It might be worth discussing whether we even need cordova-osx/cordova-mac. It sounds like "iOS apps on macOS" are going to be a thing, and in theory any cordova-ios app using WKWebView could automatically be built to support macOS as well. But that's still at least a year away...

**Comment by jcesarmobile** [comment]
closing since the platform is now deprecated
